### ISSUE TITLE
ds branch: 应用管理界面新增关闭按钮

### ISSUE THREAD

**Issue by zuohuahua** [elastos/Elastos.ORG.Wallet.Mobile#22]
![8511532156120_ pic_hd](https://user-images.githubusercontent.com/34299909/43033403-8117dc62-8cfc-11e8-9cbc-ee6d6e80423a.jpg)
因为目前我们没有‘应用切换’的概念，原设计稿中关于‘应用关闭/切换’的按钮隐藏，新增关闭按钮，具体样式如标注

**Comment by zhouhouhong** [comment]
1.1.0的版本已经添加了这个按钮。
