### ISSUE TITLE
ds branch:apk卸载不干净

### ISSUE THREAD

**Issue by raozhiming** [elastos/Elastos.ORG.Wallet.Mobile#29]
步骤：
1.手机安装了旧的Desktop，卸载
2. 再安装新的desktop

异常：发现DeskTop显示的背景及dapp都是旧的，且无法执行里面的dapp
需要手动删除sdcard里面的elastos目录，再重新安装，desktop显示的才是正确的

**Comment by zhouhouhong** [comment]
1.1.0的版本已经修复了这个bug,清验收，以前安装的时候只会覆盖原来存在的问题，并没有清空目录
