### ISSUE TITLE
交易记录页描述信息

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#35]
1. “交易输入”、“交易输出”可理解为UTXO数、地址数、金额，此处描述不明。
2. “交易输出”与“交易金额”重复，建议更改交易金额为实际支出金额即输出金额与手续费的和。
    （币种主页的最近转账记录中，建议右侧转出记录的值显示为实际指出金额：比如1.0001 ELA）

3. 交易输出，理论上包含找零输出，这里显示的值是实际到账，建议描述改为实际到账。
4. 输出地址，理论上输出地址包含找零地址，这里建议改为”收款地址“
5. 所有有关金额的值应加上单位
6. 地址与交易hash建议可点击复制，其中交易hash可改为点击复制，在右侧另增加按钮连接到区块链浏览器

**Comment by free1** [comment]
1-5，done

**Comment by JeanMaritain** [comment]
从1到5 10262已验证 6暂时不改动
