### ISSUE TITLE
所有填写信息页面中填写项目描述遮挡问题

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#37]
当前填写项目的描述显示在placeholder中，填入任何信息时placeholder消失。
若提交时发现填写错误，会难以找到需要修改的是哪一项。

涉及到的页面有：
创建钱包页、
恢复钱包页（在助记词标签页），恢复钱包页（在keystore恢复标签页）
添加联系人页

建议在列表的每一个item左上方显示描述

**Comment by songjiazhun** [comment]
@JeanMaritain  102902.apk 可以验证

**Comment by JeanMaritain** [comment]
10292 已修改
