### ISSUE TITLE
wallet-dev branch:[钱包]导入多个钱包后同步进度条显示不正常

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#45]
Android版移动端钱包，分别通过不同的私钥导入多签钱包，保证两个钱包的导入有一定的时间差，已保证同步进度有明显的进度差。

目前观察到2个Bug：
1. 通过钱包列表切换钱包，显示相同的进度条，即同步较慢的进度。
2. 在某一个钱包首页，同步进度会反复在两个不同的进度间跳变。

**Comment by songjiazhun** [comment]
已修改 两个钱包进度不会影响

**Comment by bocheng0000** [comment]
Fixed @10128.apk
