### ISSUE TITLE
wallet-dev branch:[钱包]创建多签钱包Title包含copayers字样

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#46]
Android版钱包选择语言为中文
在创建多签钱包页面，公钥数量及签名数量的Title均为英文，且所需公钥数量对应的Title为“Total number of copayers”
![s81008-140126](https://user-images.githubusercontent.com/11435265/46595494-3dfefd00-cb0b-11e8-9785-66c5eb35fa04.jpg)

**Comment by songjiazhun** [comment]
已添加中文支持

**Comment by bocheng0000** [comment]
中文版页面已调整，英文版页面还需要进行相应的调整。 @songjiazhun 
![screenshot_2018-10-09-16-49-05-834_io ionic starter](https://user-images.githubusercontent.com/11435265/46657986-2c3d5880-cbe4-11e8-83a1-2d8e818697c4.png)

**Comment by JeanMaritain** [comment]
已经添加中英文，并调整为：
("Total number of owners","拥有者数量"),
("Required number of signatures","签名数量"),
