### ISSUE TITLE
wallet-dev branch:[钱包]创建多签钱包未对签名数量进行限制

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#47]
Android版钱包
在创建多签钱包页面，选择公钥数量为4，在签名数量下拉栏可以选择超过公钥数量的签名数，并可以点击下一步。
![s81008-140126](https://user-images.githubusercontent.com/11435265/46595494-3dfefd00-cb0b-11e8-9785-66c5eb35fa04.jpg)

期待值：
签名数量应不大于公钥数量，即签名数量的可选项应根据公钥数量变化。

**Comment by songjiazhun** [comment]
已修改成 点击下一步时 签名数大于公钥数时 进行错误提示@bocheng0000

**Comment by bocheng0000** [comment]
Fixed @10128.apk
如能根据公钥数量动态调整签名数量的可选范围将更好。
