### ISSUE TITLE
wallet-dev branch:[钱包]交易手续费未根据交易大小动态计算

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#51]
Android版移动钱包
### 步骤
1. 创建单签钱包
```
select turn begin ski stove reunion hair pair patrol ripple acid moon
```

2. 向该钱包的2个地址转账，使该钱包的UTXO数量为2
3. 向钱包外地址转账
Tx:[949df940f2e0a68fc00c2af031f0cf4d32822be786de681c904b7703a834d2e8](https://blockchain-beta.elastos.org/tx/949df940f2e0a68fc00c2af031f0cf4d32822be786de681c904b7703a834d2e8)

### Bug
该交易花费了2个UTXO，但手续费与花费1个UTXO的交易一样，为0.0001ELA

**Comment by heropan** [comment]
交易费变化是每增加 1 KB变化一次, 需要尝试一下更大的交易观察一下是否变化.

**Comment by bocheng0000** [comment]
fixed@10123.apk
目前手续费最低0.0001ELA，根据交易大小变化。
