### ISSUE TITLE
wallet-dev branch:[钱包]同一个钱包再次导入相同助记词后，弹出报错信息，确定后仍弹出等待窗口

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#52]
Android版移动端钱包
### 步骤
1. 安装APP钱包后，导入助记词
```
select turn begin ski stove reunion hair pair patrol ripple acid moon
```

2. 在未删除前一个钱包的情况下，可以再次成功导入该助记词

**Comment by heropan** [comment]
@bocheng0000 fixed

**Comment by bocheng0000** [comment]
@songjiazhun 再次导入相同助记词后，弹出报错信息，确定后仍弹出等待窗口
![s81011-161320](https://user-images.githubusercontent.com/11435265/46793766-0ac1a580-cd79-11e8-9ce0-d2072abc6a1f.jpg)

**Comment by bocheng0000** [comment]
10160.apk可以按单地址模式导入相同的助记词 @heropan 
```
flat universe quantum uniform emerge blame lemon detail april sting aerobic disease
```

**Comment by heropan** [comment]
@bocheng0000 找到原因了, 已修复可以重复导入的问题.

**Comment by JeanMaritain** [comment]
import same mnemonics will not success at 10180.apk
