### ISSUE TITLE
wallet-dev branch:[钱包]错误助记词导入弹出报错信息后，仍弹出等待弹窗

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#54]
Android版移动端钱包@10101.apk
### 步骤
1. 正确助记词导入正常
```
select turn begin ski stove reunion hair pair patrol ripple acid moon
```

2. 修改助记词再次导入，无报错信息
```
select turn begin ski stove reunion hair pair patrol ripple acid good
```

**Comment by heropan** [comment]
@bocheng0000  这个我用错误的助记词会抛这个exception: {"Code":20008,"Message":"Invalid mnemonic words"}, 手机端我也试了, 也是会抛异常的.

**Comment by heropan** [comment]
@bocheng0000 抛异常以后, 界面还在转圈圈, 估计得让 @songjiazhun 看下

**Comment by bocheng0000** [comment]
@heropan 10111.apk与你描述的现象一致
![s81011-161931](https://user-images.githubusercontent.com/11435265/46794179-e2867680-cd79-11e8-8635-c715bccf40d5.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  已修复 10150.apk 可以验证

**Comment by bocheng0000** [comment]
@songsjun 现象仍存在

**Comment by JeanMaritain** [comment]
10220 可以抛出 invalid mnemonic 异常
