### ISSUE TITLE
wallet-dev branch:[钱包]开启IdChain后IdChain进度条显示错误

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#55]
Android版移动端钱包@10101.apk

### 步骤
1. 点击钱包首页右上角启用IdChain
2. 首页出现IdChain进度条，显示进度为“0%%”
![screenshot_20181010-140630](https://user-images.githubusercontent.com/11435265/46716624-67e52a80-cc97-11e8-9178-cd6ebd531f8d.jpg)

**Comment by JeanMaritain** [comment]
10180.apk before IDChain added, reduplicative '%' at sync bar not shown
