### ISSUE TITLE
wallet-dev branch:[钱包]启动钱包后白屏

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#59]
Android版移动端钱包@10110

### 步骤
1. 启动钱包
2. 显示启动图片
3. 屏幕白屏，无任何显示
![screenshot_20181011-131902](https://user-images.githubusercontent.com/11435265/46782474-e786fe00-cd58-11e8-9758-4dd5d8e43cd0.jpg)

**Comment by bocheng0000** [comment]
这些log信息是否足够？
![image](https://user-images.githubusercontent.com/11435265/46900652-27c0ba80-ced8-11e8-80ee-fe24335573cf.png)

**Comment by songjiazhun** [comment]
@bocheng0000  你这个是短时间的白屏 还是一直卡在白屏进不去

**Comment by songjiazhun** [comment]
@bocheng0000  是钱包里面存在存在相同的两个钱包造成

**Comment by bocheng0000** [comment]
基于10150.apk没有复现这个bug
目前该版本已不支持同时导入同一个钱包的助记词及keystore
