### ISSUE TITLE
wallet-dev branch:[钱包]切换钱包后会关闭原开启IdChain钱包的IdChain

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#60]
Android版移动端钱包@10110.apk

### 步骤
1. 通过助记词导入钱包，钱包名为1
```
select turn begin ski stove reunion hair pair patrol ripple acid moon
```

2. 通过该助记词再次导入钱包，钱包名为1
3. 在第二个钱包开启IdChain，显示ELA及IdChain
4. 通过钱包列表切换至第一个钱包，仅显示ELA
5. 再通过钱包列表切换至第二个钱包，仅显示ELA，在第3步开启的IDChain被关闭了。

**Comment by JeanMaritain** [comment]
10220 当前只允许存在一个 主钱包，导入两次抛出 master wallet already exist错误
