### ISSUE TITLE
wallet-dev branch:[钱包]删除钱包后钱包名依然停留在钱包列表中

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#61]
Android版移动端钱包@10110.apk

### 步骤
1. 通过助记词导入钱包，钱包名为1
```
select turn begin ski stove reunion hair pair patrol ripple acid moon
```

2. 通过该助记词再次导入钱包，钱包名为1
3. 通过第二个钱包的钱包管理删除该钱包
4. 返回钱包列表依然可以看到2个钱包
5. 点击第二个钱包弹出报错信息
![screenshot_20181011-134713](https://user-images.githubusercontent.com/11435265/46783270-31bdae80-cd5c-11e8-82ce-fa63e8c38d0d.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  这个bug一修复 下个Apk可以验证

**Comment by songjiazhun** [comment]
@bocheng0000  10.15.apk 可以验证

**Comment by bocheng0000** [comment]
Fixed @10160.apk
