### ISSUE TITLE
wallet-dev branch:[钱包]报错信息未经过滤，直接将底层报错信息返回给用户

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#62]
Android移动端钱包@10110.apk

钱包运行过程中遇到密码错误等日常错误及系统错误时，均直接将底层返回的错误信息直接以弹窗的方式反馈给用户，可读性比较差，也非常不美观。

![screenshot_20181011-145212](https://user-images.githubusercontent.com/11435265/46785852-a2b59400-cd65-11e8-95dd-5640081d99fa.jpg)
![screenshot_20181010-140719 1](https://user-images.githubusercontent.com/11435265/46785688-228f2e80-cd65-11e8-9e5f-66800258c5a7.jpg)
![screenshot_20181011-090922](https://user-images.githubusercontent.com/11435265/46785690-23c05b80-cd65-11e8-8ec0-018a253681c5.jpg)
![screenshot_20181011-092153](https://user-images.githubusercontent.com/11435265/46785691-2458f200-cd65-11e8-8639-956670879fed.jpg)
![screenshot_20181011-094727](https://user-images.githubusercontent.com/11435265/46785694-24f18880-cd65-11e8-8c89-d88a029749d4.jpg)
![screenshot_20181011-134713 1](https://user-images.githubusercontent.com/11435265/46785695-24f18880-cd65-11e8-8b86-16ce92d3c904.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  可以正常显示底层抛出的错误信息 10221.apk可以验证

**Comment by JeanMaritain** [comment]
10221 已更改样式
