### ISSUE TITLE
wallet-dev branch:[钱包]密码规则监测不稳定

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#63]
Android版移动端钱包@10110.apk

### 现象
1. 可以使用全数字密码创建或导入助记词，例如“11111111”
2. 使用全数字密码创建钱包后可以正常转账，但修改密码报错
![screenshot_20181011-151311](https://user-images.githubusercontent.com/11435265/46786723-4b64f300-cd68-11e8-9c81-9dd5dbffbf8e.jpg)

**Comment by bocheng0000** [comment]
@songjiazhun 基于10128.apk仍然可以使用全数字作为支付及私钥导出密码

**Comment by songjiazhun** [comment]
@bocheng0000  我查看的网页版钱包 js层对密码的判定 是只要长度不小于8为就可以做 支付密码 现在apk也是这个规则

**Comment by JeanMaritain** [comment]
10291 全数字支付密码可以修改密码
