### ISSUE TITLE
wallet-dev branch:[钱包]按私钥导入方式创建钱包页面不应包含助记词密码输入框

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#64]
Android版移动端钱包@10110.apk

以私钥导入的方式创建钱包，页面中除私钥密码输入框外，还有助记词密码输入框。
![screenshot_20181011-092402](https://user-images.githubusercontent.com/11435265/46786864-b9111f00-cd68-11e8-8ff4-fd3e1d7da3f0.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  已修复可以在1015.apk

**Comment by bocheng0000** [comment]
Fixed @10160.apk
