### ISSUE TITLE
wallet-dev branch:[钱包]只读多签钱包添加IdChain时，不应要求输入支付密码

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#66]
Android版移动端钱包@10110.apk

### 步骤
1. 通过3个公钥创建一个2/3的只读多签钱包
2. 通过右上角按钮开启IdChain，要求输入支付密码
![screenshot_20181011-163437](https://user-images.githubusercontent.com/11435265/46791407-acde8f00-cd73-11e8-9e05-289acfd1d62e.jpg)

因只读钱包无支付密码，所以开启IdChain也不应要求输入支付密码

**Comment by songjiazhun** [comment]
@bocheng0000  现在子钱包开启 修改不需要输入密码和单签地址

**Comment by bocheng0000** [comment]
Fixed @10160.apk
