### ISSUE TITLE
wallet-dev branch:[钱包]导入同一个钱包的keystore，程序崩溃

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#68]
当前钱包导出的keystore文本导入到当前钱包，程序崩溃

**Comment by JeanMaritain** [comment]
10111.apk

**Comment by heropan** [comment]
## Log message
[2018-10-12 10:31:18.629] [Elastos] [critical] spvsdk version v0.2.1-73-gceec8f2
10-12 10:35:08.702 23468 23637 I spvsdk  : [2018-10-12 10:35:08.702] [Elastos] [info] Master wallet init from 4, ealiest peer time = 1538701705
10-12 10:35:09.127 23468 23637 I spvsdk  : [2018-10-12 10:35:09.127] [Elastos] [info] _wallet = 0xed736dc0, listener = 0xd178dcf0
10-12 10:35:09.133 23468 23637 I spvsdk  : peer manager found 3 peers
10-12 10:35:09.133 23468 23637 I spvsdk  : manager->peers[0] = 13.210.251.118
10-12 10:35:09.133 23468 23637 I spvsdk  : manager->peers[1] = 18.194.136.248
10-12 10:35:09.133 23468 23637 I spvsdk  : manager->peers[2] = 35.177.55.45
10-12 10:35:09.133 23468 23637 I spvsdk  : 13.210.251.118:21866 connecting
10-12 10:35:09.134 23468 23637 I spvsdk  : 18.194.136.248:21866 connecting
10-12 10:35:09.134 23468 23637 I spvsdk  : 35.177.55.45:21866 connecting
10-12 10:35:09.134 23468 23637 I spvsdk  : [2018-10-12 10:35:09.134] [Elastos] [info] Going to save configuration of subwallet 'ELA'
10-12 10:35:09.202 24294 23637 F google-breakpad: -----BEGIN BREAKPAD MICRODUMP-----
10-12 10:35:09.202 24294 23637 F google-breakpad: V AndroidWebView:62.0.3202.84

## Java action and parameters
action = 'importWalletWithKeystore'

args = ["7E7C1D","{\"adata\":\"\",\"cipher\":\"aes\",\"ct\":\"p6KV8Mnp47ZFbrnI5OYUY3GZ6dfy93FaMLBRcKNO7GmIlnpKGFlv0D27OX\/dODHlU+JV9KYyb\/o3\\r\\ngZe4mwM+SZgi9Zeo7qp0yzogPMryQKCYVPe3iBzs5ifJ1X5sTyuAjHr5KlwJYNeG3EZYe4WilG8I\\r\\nV5sztNNoFH1fDHFjQFeBDSo1Uy\/7opXhtWy1hXTHTrpa4JPPKVKp3kufzLzDBNyB9oXRVJdyEetY\\r\\nxV\/1T4EuO8EssHl1oQuFMbWU3Qd1atz8ZUiIknp+C9lUA3UL4RytZwYp+r8f1l6wnuQMzCC5p4CV\\r\\nLhxu6w2aWOKlTc+5RnBMWXQEUnql0dOqfpADqT6B9mDkoMyUBaI4ZUnbdNqeQKPGJ0987hGcBhPR\\r\\no2a+kj6I\/NkHdYEGqXFmKQK86\/TEZNTzt3wwAqDe7CRQVHkYb0F5ae58SmIsWKlC8o2b+xge4MWK\\r\\nDgu9j3zjmVK92fKj3EbVV9Ueea2Vv1bDyPD0OZyTu8Z+NSOkk92+Q+xnsAi\/nZ9hhsoDe9\/j7yP9\\r\\n9X8jKPSE\/y7m7cx\/kYirRgjn9PDjcr8PQwtVZH6B6b5hNN3nMeIgiUz1RNma1KZFbpWve99wThLy\\r\\nSe5dtAEQ0AISXi6Z241Q+Zx+YDkkG4hptmSswbXUr98kGNuR3R3UdrlU8zFXTJpSwXapNLa+B+k2\\r\\nTiol05WVrYwMsQv4ALFxy96R7AJOo1eWCexrD\/awS+pca\/q48g9qkXnBEfep1dT22WgAAVdkd7r2\\r\\nn59A0A3ig\/aLqCej3n\/QfQiJxZQI72pcw3zc7LltkEn+TD5WRsOhwcYl2zcMpMeQHSVt37D85QyG\\r\\nZSCe8Tuh3BAjuGd1I5hxV2\/XXpThJGl4eIkTm1XNOVU\/LDTXKOGrAdbh5TFMQyKLbXpi0SzkQHWR\\r\\nF3X2Y83TgB6sv5XSf4N5TqzVsFaz8JoeM10EseC3tJXP5Rt\/J2dHuHiPsDkTgDwlmlrO8+QJVhOX\\r\\njtycnelM2oFmuNTIMxtI2ixvbvgcFuXYwsUfm2uaDaMV5BAyvtX2sN4dxptaOMRhTxtazVfiWR79\\r\\nxQ\/\/jsPQoHj20uSnJqoyXq3qTCPs0bKVAHoi3o\/s9ZX+6SDrWs35haIpysZcyFcP2K6Imrozq4gZ\\r\\nHZ\/\/QPZDKSGW++aGbXtBGeOtGjcb5Sn\/mV\/PTJBJ4uLCqVIdqYWENQoFYo8QVQiAuSQvfSzwmeGu\\r\\nLuRcDSldJ18Zohw=\",\"iter\":10000,\"iv\":\"vXqUECUBRKYdfqFSmtrikQ==\",\"ks\":256,\"mode\":\"ccm\",\"salt\":\"wWqFtdddf\/w=\",\"ts\":64,\"v\":1}","asdfasdf1","asdfasdf1",""]


## backtrace
10-12 10:35:09.229 23468 23637 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
10-12 10:35:09.229 23468 23637 W google-breakpad: Chrome build fingerprint:
10-12 10:35:09.229 23468 23637 W google-breakpad: 0.1
10-12 10:35:09.229 23468 23637 W google-breakpad: 100
10-12 10:35:09.229 23468 23637 W google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
10-12 10:35:09.229 23468 23637 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 23637 (JavaBridge), pid 23468 (o.ionic.starter)
10-12 10:35:09.334 24297 24297 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
10-12 10:35:09.335   923   923 I /system/bin/tombstoned: received crash request for pid 23468
10-12 10:35:09.336 24297 24297 I crash_dump32: performing dump of process 23468 (target tid = 23637)
10-12 10:35:09.337 24297 24297 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-12 10:35:09.337 24297 24297 F DEBUG   : Build fingerprint: 'Xiaomi/dipper/dipper:8.1.0/OPM1.171019.026/V10.0.6.0.OEACNFH:user/release-keys'
10-12 10:35:09.337 24297 24297 F DEBUG   : Revision: '0'
10-12 10:35:09.337 24297 24297 F DEBUG   : ABI: 'arm'
10-12 10:35:09.337 24297 24297 F DEBUG   : pid: 23468, tid: 23637, name: JavaBridge  >>> io.ionic.starter <<<
10-12 10:35:09.337 24297 24297 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
10-12 10:35:09.337 24297 24297 F DEBUG   : Cause: null pointer dereference
10-12 10:35:09.337 24297 24297 F DEBUG   :     r0 00000000  r1 d088272c  r2 00000000  r3 00000000
10-12 10:35:09.337 24297 24297 F DEBUG   :     r4 d088272c  r5 f0644c80  r6 2fb12803  r7 d0882718
10-12 10:35:09.337 24297 24297 F DEBUG   :     r8 00000000  r9 e55d3000  sl d0882830  fp d08827bc
10-12 10:35:09.337 24297 24297 F DEBUG   :     ip 00000000  sp d0882650  lr 00000000  pc d4ea2de6  cpsr 60010030
10-12 10:35:09.337 24297 24297 F DEBUG   :
10-12 10:35:09.337 24297 24297 F DEBUG   : backtrace:
10-12 10:35:09.338 24297 24297 F DEBUG   :     #00 pc 0001ade6  /data/app/io.ionic.starter-NF3_kmnpxSQP6WvnB05hLg==/lib/arm/libelastoswallet.so
10-12 10:35:09.338 24297 24297 F DEBUG   :     #01 pc 0000b373  /data/app/io.ionic.starter-NF3_kmnpxSQP6WvnB05hLg==/oat/arm/base.odex (offset 0xa000)

**Comment by heropan** [comment]
@JeanMaritain fixed

**Comment by JeanMaritain** [comment]
已修复，不崩溃，
弹出：
错误信息:{" error":{"code
20005, message: Import(6E21 B8)with
keystore: Master wallet already exist. 3)
