### ISSUE TITLE
wallet-dev branch:[钱包]创建单地址钱包，地址管理中仍然是多地址

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#69]

**Comment by bocheng0000** [comment]
最好补充钱包助记词及截屏信息，便于现象复现 @JeanMaritain

**Comment by JeanMaritain** [comment]
![createwalletpage](https://user-images.githubusercontent.com/17795520/46847832-08168d00-ce19-11e8-908c-be7ff98a3976.png)
![receivepage](https://user-images.githubusercontent.com/17795520/46847833-08168d00-ce19-11e8-8523-6dd6763a016d.png)

**Comment by bocheng0000** [comment]
与 #77 相同
@JeanMaritain
