### ISSUE TITLE
wallet-dev branch:[钱包]币种列表打开IDchain时选择单地址，关闭后再打开不应重复选择是否单地址

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#72]
'app-debug(8).apk'

币种列表打开IDchain时选择单地址，关闭后再打开不应重复选择是否单地址。
因为不论下次打开选择是否单地址，实际地址列表中显示的钱包地址类型依然为第一次打开IDchain时的选择。

**Comment by songjiazhun** [comment]
@JeanMaritain  现在开启子钱包修改为不需要输入密码和选择单签地址

**Comment by JeanMaritain** [comment]
已验证
