### ISSUE TITLE
wallet-dev branch:[钱包]首页余额在同步完成后不能自动显示

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#75]
Android版移动端钱包@10123.apk

### 步骤
1. 导入助记词
```
select turn begin ski stove reunion hair pair patrol ripple acid moon
```
2. 停留在钱包也等待同步结束
![screenshot_20181012-120705](https://user-images.githubusercontent.com/11435265/46847695-3e074180-ce18-11e8-9e6f-c62c0592a65b.jpg)
3. 点击“ELA”查看交易记录，可见余额及交易记录
![screenshot_20181012-122256](https://user-images.githubusercontent.com/11435265/46847952-9428b480-ce19-11e8-92f4-eee6c35189aa.jpg)
4. 再返回首页，有余额显示
![screenshot_20181012-122402](https://user-images.githubusercontent.com/11435265/46847972-bae6eb00-ce19-11e8-950a-7fb77dc3ed2f.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  已解决

**Comment by bocheng0000** [comment]
@songjiazhun 基于10128.apk仍然有这个问题，可以尝试导入助记词，复现概率较高
```
flat universe quantum uniform emerge blame lemon detail april sting aerobic disease
```

**Comment by songjiazhun** [comment]
好 我试一下@bocheng0000

**Comment by songjiazhun** [comment]
@bocheng0000  这个助记词 同步时余额只能到735.340475699 然后就没收到下层余额通知 需要英雄看下@heropan

**Comment by songjiazhun** [comment]
实际余额是772.01046259 @heropan

**Comment by heropan** [comment]
@bocheng0000 fixed

**Comment by JeanMaritain** [comment]
已验证 flat universe quantum uniform emerge blame lemon detail april sting aerobic disease 和 select turn begin ski stove reunion hair pair patrol ripple acid moon 
10132.apk 可以同步
