### ISSUE TITLE
wallet-dev branch:[钱包]新创建钱包，直接查看接收地址，该地址未在地址列表中显示

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#76]
Android版移动端钱包@10123.apk

### 步骤
1. 创建新的钱包，得到助记词为
```
perfect car luggage fold sugar cradle fever arrow edit stick give sadness
```
2. 进入ELA页面，点击接收，显示接收地址为**ERmEJEGbBdQFXL4uASvdMEZWfNN3oHZewM**
![screenshot_20181012-140006](https://user-images.githubusercontent.com/11435265/46850740-942fb100-ce27-11e8-8305-e7967c7e1804.jpg)
3. 点击地址管理，地址列表中未显示地址**ERmEJEGbBdQFXL4uASvdMEZWfNN3oHZewM**
![screenshot_20181012-140013](https://user-images.githubusercontent.com/11435265/46850739-92fe8400-ce27-11e8-9aad-bf0bb5e338ea.jpg)

**Comment by heropan** [comment]
@bocheng0000 这个地址在底层是有的, 这个是上层的bug, 获取地址没有按分页处理, 只是获取了固定个数的地址.

**Comment by songjiazhun** [comment]
@bocheng0000  现在添加分页查询 10221.apk

**Comment by JeanMaritain** [comment]
10221 已在地址列表中显示
