### ISSUE TITLE
wallet-dev branch:[钱包]只读多签钱包添加IdChain时，不应显示“单地址钱包”选项

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#80]
Android版移动端钱包@10128.apk

### 步骤
1. 通过公钥导入只读多签钱包
```
032f4540e915134f38ba24cdc08621ad7f5b8b62db36843ae8fa9422c047a04be8
02e63efab72413b320a341b054d5d6ce5f1565a3b466aa4925de69d152027cce20
02f212915764714d1a7cc85100d924f4657e7797da269ea2eb4968146e57ca364c
02f3346a807786c4d040c7f7df75b2f4b64cc6f9f95aaf0bed79099fb1c48fdb3f
```

2. 开启IdChain，弹出对话框包含“单地址钱包”选项及支付密码，该2项不应出现在只读多签钱包页面。
![screenshot_20181012-235723](https://user-images.githubusercontent.com/11435265/46880845-5f9a1480-ce7c-11e8-8ace-40e674516208.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  开启子钱包不需要选择密码和是否为单签地址 可以再10150.apk 验证

**Comment by bocheng0000** [comment]
Fix @10160.apk
