### ISSUE TITLE
wallet-dev branch:[钱包]接受页 当前地址 字体过小

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#84]
![screenshot-1539421224732](https://user-images.githubusercontent.com/17795520/46903566-894d4d00-cf09-11e8-99d0-a60289144106.jpg)

**Comment by JeanMaritain** [comment]
10128.apk

**Comment by songjiazhun** [comment]
@JeanMaritain  已修改 可在10150.apk 验证

**Comment by JeanMaritain** [comment]
已验证
