### ISSUE TITLE
wallet-dev branch:[钱包]导入钱包，无响应，应有提示

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#85]
网络状况不佳时，导入钱包点击确认后会停在导入页，操作无响应，此处应有提示程序正在导入中，需要用户等待。

"wallet_name": "ElaPayAutoTest_01Oct_12_10:48:58",
"pay_code": "asdfasdf1",
"single_addr": True,
"o_pswd": "",
"mnes": "huge skull bronze fiction holiday defy throw file panda crumble bean hope"

![image](https://user-images.githubusercontent.com/17795520/46903820-41c8c000-cf0d-11e8-8d41-7ff0aa88d87a.png)

**Comment by songjiazhun** [comment]
@JeanMaritain  已添加loading 10160.apk 可以验证

**Comment by JeanMaritain** [comment]
已验证
