### ISSUE TITLE
wallet-dev branch:联系人添加成功后页面跳转问题

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#86]
联系人添加成功后，返回按钮不应该导航至仍然带有已填信息的添加联系人页

**Comment by JeanMaritain** [comment]
以及联系人页点击删除按钮应增加弹出确认取消删除操作的alert，取消提示已经删除的alert。
联系人页删除后页面应该刷新。

**Comment by songjiazhun** [comment]
@JeanMaritain  已修复可以再10151.apk 验证

**Comment by JeanMaritain** [comment]
已验证
