### ISSUE TITLE
ds branch: app管理界面，列表点击热区错误

### ISSUE THREAD

**Issue by zuohuahua** [elastos/Elastos.ORG.Wallet.Mobile#9]
现在是点击右边箭头进入下一级界面，点击其他区域选中。
设计是点击checkbox选中，其他区域进入下一级界面。

**Comment by zuohuahua** [comment]
点击到空白区域不能进入下一级，必须点击到图标或者文字上才有效
test commit: 709ae69ecd610ecf4e879f306fc10eabae08baab

**Comment by zuohuahua** [comment]
错误操作关闭了，重新打开

**Comment by zhouhouhong** [comment]
1.1.0的版本已经解决了这个问题
