### ISSUE TITLE
wallet-dev branch:[mobile wallet] receive amount error

### ISSUE THREAD

**Issue by JeanMaritain** [elastos/Elastos.ORG.Wallet.Mobile#94]
wallet: 
huge skull bronze fiction holiday defy throw file panda crumble bean hope
tx in 1 ela:
from EHB3pkgZW6UJKaFq1GYS1acxmrSfeXA6N3
to ETHDNNMSXm1YVJ7yjyakqydr3UUCnhn5jF
https://blockchain-beta.elastos.org/tx/7e6b1d8d8b299de895bf1199d6621b7928ec96138f87f370babdfc603ad5f2b4

tx fee 0.0000486ela already taken by miner

wallet balance show 0.9999514, should be 1ela

**Comment by free1** [comment]
fixed

**Comment by JeanMaritain** [comment]
verified at 10230.apk
