### ISSUE TITLE
wallet-dev branch:[wallet app]Wallet name has no length limit

### ISSUE THREAD

**Issue by bocheng0000** [elastos/Elastos.ORG.Wallet.Mobile#95]
### Version
10260.apk

### Phenomenon
1. Import the mnemonic
2. Change the wallet name to a string of 100 characters in length.
![screenshot_20181026-155804](https://user-images.githubusercontent.com/11435265/47552763-1051ea80-d938-11e8-82aa-a4ddd9e9d151.jpg)
![screenshot_20181026-155809](https://user-images.githubusercontent.com/11435265/47552764-10ea8100-d938-11e8-8163-68debe095a81.jpg)

**Comment by songjiazhun** [comment]
@bocheng0000  10290.apk 可以验证

**Comment by JeanMaritain** [comment]
10291 已验证
